# Generated by Django 5.0.14 on 2026-09-24 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK', 'Ngân hàng'), ('OTHER', 'Khác')], default='BANK', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opening_date', models.DateField()),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('counterparty_type', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('SUPPLIER', 'Nhà cung cấp'), ('EMPLOYEE', 'Nhân viên'), ('OTHER', 'Khác')], default='OTHER', max_length=20)),
                ('tax_code', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('INACTIVE', 'Ngừng sử dụng')], default='ACTIVE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cashflow.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Thu'), ('EXPENSE', 'Chi'), ('TRANSFER', 'Chuyển nội bộ')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Đã duyệt - chưa thực hiện'), ('COMPLETED', 'Đã thực hiện')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cashflow.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cashflow_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_cashflow_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cashflow.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cashflow_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Tiền vào'), ('OUT', 'Tiền ra')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cashflow.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cashflow.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='cashflow_tr_transac_bf6099_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_date'], name='cashflow_tr_status_e19061_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='cashflow_tr_transac_4c55b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['account', 'direction'], name='cashflow_tr_account_91864c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transaction_entry_amount_gt_zero'),
        ),
    ]
