# Generated by Django 5.0.14 on 2026-09-24 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'ordering': ['name'], 'verbose_name': 'Người gửi / nhận', 'verbose_name_plural': 'Người gửi / nhận'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['code'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-id'], 'verbose_name': 'Giao dịch', 'verbose_name_plural': 'Giao dịch'},
        ),
        migrations.AlterModelOptions(
            name='transactionentry',
            options={'verbose_name': 'Biến động tài khoản', 'verbose_name_plural': 'Biến động tài khoản'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Mã giao dịch'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số tài khoản'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK', 'Ngân hàng'), ('OTHER', 'Khác')], default='BANK', max_length=20, verbose_name='Loại tài khoản'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã tài khoản'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên tài khoản'),
        ),
        migrations.AlterField(
            model_name='account',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Số dư ban đầu'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Mã đối tác'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='counterparty_type',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('SUPPLIER', 'Nhà cung cấp'), ('EMPLOYEE', 'Nhân viên'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Loại đối tác'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên người gửi / nhận'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cashflow.counterparty', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('INACTIVE', 'Ngừng sử dụng')], default='ACTIVE', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cashflow.counterparty', verbose_name='Người gửi / nhận'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cashflow_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_cashflow_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cashflow.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Đã duyệt - chưa thực hiện'), ('COMPLETED', 'Đã thực hiện')], default='COMPLETED', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(verbose_name='Ngày phát sinh'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Thu'), ('EXPENSE', 'Chi'), ('TRANSFER', 'Chuyển nội bộ')], max_length=20, verbose_name='Thu / Chi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cashflow_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cashflow.account', verbose_name='Tài khoản biến động'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='direction',
            field=models.CharField(choices=[('IN', 'Tiền vào'), ('OUT', 'Tiền ra')], max_length=10, verbose_name='Chiều biến động'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cashflow.transaction', verbose_name='Giao dịch'),
        ),
    ]
