# Generated by Django 5.0.14 on 2026-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_account_options_alter_counterparty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('REPAIR', 'Sửa chữa'), ('PRODUCTION', 'Sản xuất'), ('DEVELOPMENT', 'Phát triển')], default='', max_length=20, verbose_name='Loại đơn hàng'),
        ),
    ]
